default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: rezzemay_api_development

test:
  <<: *default
  database: rezzemay_api_test

production:
  <<: *default
  database: rezzemay_api_production
  username: rezzemay_api
  password: <%= ENV['REZZEMAY_DATABASE_PASSWORD'] %>
